<<<<<<< HEAD
# Generated by Django 6.0 on 2026-01-08 09:27
=======
# Generated by Django 5.2.6 on 2026-01-10 20:21
>>>>>>> 7ee9b21 (Inital at 01.12.2026)

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('address_id', models.UUIDField(blank=True, null=True)),
                ('attrs', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id_fme', models.TextField(primary_key=True, serialize=False)),
                ('fme_levels', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fme_height', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('h3_id', models.TextField(blank=True, null=True)),
                ('h3_res', models.SmallIntegerField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
<<<<<<< HEAD
=======
                ('status', models.CharField(choices=[('free', 'free'), ('for_sale', 'for_sale'), ('sold', 'sold'), ('fractional', 'fractional')], default='free', max_length=20)),
                ('total_shares', models.IntegerField(default=1)),
>>>>>>> 7ee9b21 (Inital at 01.12.2026)
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('referral_email', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
<<<<<<< HEAD
=======
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('vat_number', models.CharField(blank=True, max_length=50, null=True)),
>>>>>>> 7ee9b21 (Inital at 01.12.2026)
                ('code', models.CharField(blank=True, max_length=6, null=True)),
                ('vat', models.CharField(blank=True, max_length=15, null=True)),
                ('stripe_account_id', models.CharField(blank=True, max_length=255, null=True)),
                ('stripe_kyc', models.BooleanField(default=False)),
                ('user_range', models.IntegerField(db_index=True, default=1)),
<<<<<<< HEAD
=======
                ('two_factor_enabled', models.BooleanField(default=False)),
>>>>>>> 7ee9b21 (Inital at 01.12.2026)
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
<<<<<<< HEAD
                ('share_count', models.IntegerField(default=1)),
                ('left_shares', models.IntegerField()),
                ('status', models.CharField(choices=[('active', 'active'), ('pending', 'pending'), ('cancelled', 'cancelled')], default='active', max_length=20)),
=======
                ('currency', models.CharField(default='PLN', max_length=10)),
                ('share_count', models.IntegerField(default=1)),
                ('left_shares', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'active'), ('pending', 'pending'), ('cancelled', 'cancelled')], default='active', max_length=20)),
                ('valid_from', models.DateTimeField(auto_now_add=True)),
>>>>>>> 7ee9b21 (Inital at 01.12.2026)
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='logic.house')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_received', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_sent', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'pending'), ('accepted', 'accepted'), ('blocked', 'blocked')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
<<<<<<< HEAD
                ('friend', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='friend_requests_received', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='friend_requests_sent', to=settings.AUTH_USER_MODEL)),
=======
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_requests_received', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_requests_sent', to=settings.AUTH_USER_MODEL)),
>>>>>>> 7ee9b21 (Inital at 01.12.2026)
            ],
            options={
                'unique_together': {('user', 'friend')},
            },
        ),
        migrations.CreateModel(
            name='HouseOwnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('shares', models.IntegerField()),
                ('bought_for', models.IntegerField()),
=======
                ('shares', models.IntegerField(default=0)),
                ('bought_for', models.IntegerField(blank=True, null=True)),
>>>>>>> 7ee9b21 (Inital at 01.12.2026)
                ('house', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='ownerships', to='logic.house')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='house_ownerships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('house', 'user')},
            },
        ),
    ]
