# Generated by Django 5.2.7 on 2025-11-01 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0001_initial'),
    ]

    operations = [
    ]
