# Generated by Django 5.2.6 on 2026-01-24 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0003_add_transaction_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
