# Generated by Django 5.2.7 on 2025-11-01 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0002_fix_address_field'),
        ('logic', '0003_fix_address_field'),
    ]

    operations = [
    ]
