# Generated by Django 5.2.7 on 2025-11-01 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0004_merge_0002_fix_address_field_0003_fix_address_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='referral_email',
            field=models.CharField(blank=True, db_column='referral_email', max_length=255, null=True),
        ),
    ]
