# Generated by Django 5.2.7 on 2025-11-03 11:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0005_user_address_user_referral_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.UUIDField(db_column='id', primary_key=True, serialize=False)),
                ('house', models.UUIDField(db_column='house_id')),
                ('seller', models.BigIntegerField(db_column='seller_id')),
                ('price', models.DecimalField(db_column='price', decimal_places=2, max_digits=12)),
                ('currency', models.CharField(db_column='currency', default='PLN', max_length=10)),
                ('status', models.TextField(db_column='status')),
                ('valid_from', models.DateTimeField(blank=True, db_column='valid_from', null=True)),
                ('valid_to', models.DateTimeField(blank=True, db_column='valid_to', null=True)),
            ],
            options={
                'db_table': '"market"."listings"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.UUIDField(db_column='id', primary_key=True, serialize=False)),
                ('listing', models.UUIDField(db_column='listing_id')),
                ('buyer', models.BigIntegerField(db_column='buyer_id')),
                ('seller', models.BigIntegerField(db_column='seller_id')),
                ('amount', models.DecimalField(db_column='amount', decimal_places=2, max_digits=12)),
                ('currency', models.CharField(db_column='currency', default='PLN', max_length=10)),
                ('status', models.TextField(db_column='status')),
                ('created_at', models.DateTimeField(blank=True, db_column='created_at', null=True)),
            ],
            options={
                'db_table': '"trade"."trades"',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='fa',
            name='user_id',
        ),
        migrations.AddField(
            model_name='fa',
            name='user',
            field=models.OneToOneField(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fa', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='active', max_length=20)),
                ('listing_id', models.UUIDField(blank=True, null=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations_as_buyer', to=settings.AUTH_USER_MODEL)),
                ('house', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='logic.house')),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations_as_seller', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField(blank=True, default='')),
                ('schema_id', models.IntegerField(blank=True, null=True)),
                ('message_type', models.CharField(default='normal', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='logic.conversation')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['buyer'], name='logic_conve_buyer_i_f6e078_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['seller'], name='logic_conve_seller__df3a11_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['house'], name='logic_conve_house_i_4096bf_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['created_at'], name='logic_conve_created_564481_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'created_at'], name='logic_messa_convers_bae547_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', 'created_at'], name='logic_messa_sender__2cfe1f_idx'),
        ),
    ]
