# Generated by Django 5.2.7 on 2025-11-03 11:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0006_listing_trade_remove_fa_user_id_fa_user_conversation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fa',
            name='user',
            field=models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='fa', to=settings.AUTH_USER_MODEL),
        ),
    ]
