# Generated by Django 5.2.7 on 2025-11-03 22:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0010_offer_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='conversation',
            new_name='conversatio_created_207cdb_idx',
            old_name='logic_conve_created_564481_idx',
        ),
        migrations.RenameIndex(
            model_name='conversation',
            new_name='conversatio_house_i_fdd1af_idx',
            old_name='logic_conve_house_i_4096bf_idx',
        ),
        migrations.RenameIndex(
            model_name='conversation',
            new_name='conversatio_buyer_i_67b226_idx',
            old_name='logic_conve_buyer_i_f6e078_idx',
        ),
        migrations.RenameIndex(
            model_name='conversation',
            new_name='conversatio_seller__96a9b1_idx',
            old_name='logic_conve_seller__df3a11_idx',
        ),
        migrations.RenameIndex(
            model_name='message',
            new_name='message_convers_5aa82f_idx',
            old_name='logic_messa_convers_bae547_idx',
        ),
        migrations.RenameIndex(
            model_name='message',
            new_name='message_sender__8e11cb_idx',
            old_name='logic_messa_sender__2cfe1f_idx',
        ),
        migrations.RenameIndex(
            model_name='offer',
            new_name='offer_convers_c38059_idx',
            old_name='offer_convers_created_idx',
        ),
        migrations.AlterField(
            model_name='conversation',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('agreed', 'agreed'), ('sold', 'sold'), ('stopped', 'stopped')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('normal', 'normal'), ('text', 'text'), ('offer', 'offer'), ('counter_offer', 'counter_offer'), ('agreement', 'agreement'), ('system', 'system')], default='normal', max_length=20),
        ),
        migrations.AlterField(
            model_name='offer',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='offer',
            name='type',
            field=models.CharField(choices=[('offer', 'offer'), ('counter', 'counter')], max_length=16),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(fields=('house', 'buyer', 'seller'), name='uq_conv_house_buyer_seller'),
        ),
    ]
