# Generated by Django 5.2.7 on 2025-11-10 16:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0011_rename_logic_conve_created_564481_idx_conversatio_created_207cdb_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Negotiation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('conversation_id', models.UUIDField(db_index=True, unique=True)),
                ('house_id', models.UUIDField(db_index=True)),
                ('buyer_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('seller_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('last_offer_by', models.CharField(blank=True, choices=[('buyer', 'buyer'), ('seller', 'seller')], max_length=8, null=True)),
                ('accepted_by', models.CharField(blank=True, choices=[('buyer', 'buyer'), ('seller', 'seller')], max_length=8, null=True)),
                ('agreed_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('status', models.CharField(choices=[('open', 'open'), ('accepted', 'accepted'), ('finalized', 'finalized'), ('stopped', 'stopped')], default='open', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='neg_as_buyer', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='neg_as_seller', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'messages_negotiation',
                'indexes': [models.Index(fields=['conversation_id'], name='messages_ne_convers_1e8d54_idx'), models.Index(fields=['house_id'], name='messages_ne_house_i_38b4c4_idx')],
            },
        ),
    ]
