# Generated by Django 5.2.7 on 2025-11-16 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0012_negotiation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ai_auto_reply',
            field=models.BooleanField(default=False),
        ),
    ]
