# Generated by Django 5.2.7 on 2025-11-19 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0013_user_ai_auto_reply'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseOwnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shares', models.PositiveIntegerField(db_column='shares')),
            ],
            options={
                'db_table': '"catalog"."house_ownership"',
                'managed': False,
            },
        ),
    ]
