# Generated by Django 5.2.7 on 2025-11-20 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0014_houseownership'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='shares',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
