# Generated by Django 5.2.7 on 2025-11-20 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0015_offer_shares'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('normal', 'normal'), ('text', 'text'), ('offer', 'offer'), ('counter', 'counter'), ('agreement', 'agreement'), ('system', 'system')], default='normal', max_length=20),
        ),
    ]
