# Generated by Django 5.2.7 on 2025-11-21 16:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0016_alter_message_message_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareSplitProposal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_total_shares', models.PositiveIntegerField()),
                ('requested_total_shares', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('open', 'open'), ('applied', 'applied'), ('cancelled', 'cancelled')], default='open', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('house', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='split_proposals', to='logic.house')),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiated_split_proposals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"ownership"."share_split_proposal"',
            },
        ),
        migrations.CreateModel(
            name='ShareSplitVote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vote', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='logic.sharesplitproposal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"ownership"."share_split_vote"',
            },
        ),
        migrations.AddIndex(
            model_name='sharesplitproposal',
            index=models.Index(fields=['house', 'status'], name='share_split_house_i_2e7962_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sharesplitvote',
            unique_together={('proposal', 'user')},
        ),
    ]
