# Generated by Django 5.2.7 on 2025-11-21 17:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0017_sharesplitproposal_sharesplitvote_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SplitLimitRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requested_max_shares', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected'), ('cancelled', 'cancelled')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='split_limit_decisions', to=settings.AUTH_USER_MODEL)),
                ('house', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='split_limit_requests', to='logic.house')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='split_limit_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"ownership"."split_limit_request"',
                'indexes': [models.Index(fields=['house', 'status'], name='split_limit_house_i_64b1d8_idx')],
            },
        ),
    ]
