# Generated by Django 5.2.7 on 2025-11-25 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0018_splitlimitrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_range',
            field=models.IntegerField(db_index=True, default=1),
        ),
    ]
