# Generated by Django 5.2.7 on 2025-11-26 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0019_user_user_range'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('alt', models.FloatField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('type', models.CharField(default='user', max_length=16)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='map_position', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
