# Generated by Django 5.2.7 on 2025-11-27 08:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0020_userposition'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direct_messages_received', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direct_messages_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"messaging"."direct_chat_message"',
                'indexes': [models.Index(fields=['sender', 'receiver', 'created_at'], name='direct_chat_sender__cba6f7_idx'), models.Index(fields=['receiver', 'sender', 'created_at'], name='direct_chat_receive_06c3a4_idx')],
            },
        ),
    ]
