# Generated by Django 5.2.7 on 2025-11-28 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0021_directchatmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPosition',
        ),
    ]
