# Generated by Django 5.2.7 on 2025-12-03 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0024_chatsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_chats', to=settings.AUTH_USER_MODEL)),
                ('peer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"messaging"."saved_chat"',
                'unique_together': {('owner', 'peer')},
            },
        ),
    ]
